### ISSUE TITLE
Theme Color - Loss

### ISSUE THREAD

**Issue by developerkamlesh00** [greven/umbra-vscode-theme#3]
Hii , 
Please help me with the color update. After updating the extension, I lost the red theme color, and it currently looks like cyan
I have switched back to v0.3.4 and now it's working fine.
**Is this the intended behavior for the update?**

<img width="847" alt="image" src="https://github.com/greven/umbra-vscode-theme/assets/129079007/47c19ecd-2eb1-4711-bdff-c3ae6e50e187">

**Comment by Mavirk** [comment]
Fully agree, don't know what happened, But this is my favorite color theme, and for some reason everything has changed. 
I mean I fully support a dev keeping his stuff updated etc, and I fully appreciate that, but 1.x.x seems to be a totally breaking change. Is there a specific reason for why the changes have been made, 
PS reverted back to 0.3.3 for my beloved colors

**Comment by greven** [comment]
Hey. I didn't even know people used this theme. :)
I felt the buttons had a low contrast so made them blueish.
The syntax colors had tweaks too, but I will add a version of the theme with the old colors then. :)

**Comment by greven** [comment]
Hey. I didn't even know people used this theme. :)
I felt the buttons had a low contrast so made them blueish.
The syntax colours had tweaks too, but I will add a version of the theme with the old colors then. :)

Can I ask for feedback what is the biggest issues you have with the changes?
- The syntax tweaks to the syntax colours?
- The new colours for buttons (take into account buttons are barely visible anywhere in VS Code in the UI)?
- The UI is generally darker (the foreground of the editor is now darker as I felt it was a bit too light, specially since I wanted Umbra to be... dark, since that is what Umbra means. :P).

Please leave some feedback as I want to understand what is the biggest issues with the update.
Thanks.

Nuno.

**Comment by Mavirk** [comment]
Personally, my biggest issue was syntax color changes. Maybe a suggestion would be a "legacy" color pallette. I'm ok with the button changes but I think matching the purple or red color would be best instead of the jarring cyan.

**Comment by greven** [comment]
I was actually re-doing becauseI felt sometimes the theme was well mapped to some tokens and the blue was already there but it was a darker shade that what it is now.
I will add anyway a theme variation with the old colours (with some adjustments to the UI anyway to make it a bit darker).

Thanks for the feedback.

**Comment by developerkamlesh00** [comment]
Hey @greven 
The update looks awesome. I have gone through it, and it seems that some shades are broken. 
here Install Button Texts
<img width="369" alt="image" src="https://github.com/greven/umbra-vscode-theme/assets/129079007/3ce8f259-0fa5-4a5e-9c7f-ce3cb161dfa5">
One more like in Syntax for Custom Component Tags and Text Colors Looks Same #White
<img width="385" alt="image" src="https://github.com/greven/umbra-vscode-theme/assets/129079007/9bceca58-f4cf-4de6-83fd-d4a07549ae69">

Rest Looks Good.
Waiting for the next update change, which has more darkness and color contrast.

**Comment by greven** [comment]
Thanks for the feedback. That problem in the buttons is not normal. Nor the background color shown there, it looks like brown. Somehow something is interfering with the theme. :)

**Comment by greven** [comment]
Hey. Reverted some changes, toned down some colours too.
Maintained the darker background of the editor and changed the strings colours since there wasn't enough contrast.
I will eventually add some theme variations with different syntax colours. :)

**Comment by developerkamlesh00** [comment]
> Hey. Reverted some changes, toned down some colours too. Maintained the darker background of the editor and changed the strings colours since there wasn't enough contrast. I will eventually add some theme variations with different syntax colours. :)

Yeah, sounds good.
